app1/urls.py
from django.urls import path
from app1.views import *
app_name='anushka'

urlpatterns=[
    path('arundathi/',arundathi,name='arundathi'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='pasupathi'

urlpatterns=[
    path('pasupathi/',pasupathi,name='pasupathi'),
]

project10/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def arundathi(request):
    return render(request,'arundathi.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def pasupathi(request):
    return render(request,'pasupathi.html')

templates/arundathi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Nuv nannem cheyalev raa!!!!</h1>
        <h1>Action</h1>
        <h2><a href='{% url "pasupathi:pasupathi" %}'>Dialouge of pasupathi</a></h2>
    </center>
    
</body>
</html>

templates/pasupathi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Vadala bommali vadalaaa.......</h1>
        <h1>Action</h1>
        <h2><a href='{% url "anushka:arundathi" %}'>Dialouge of anushka</a></h2>
    </center>
    
</body>
</html>